apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart2
spec:
  selector:
    matchLabels:
      app: cart2
  template:
    metadata:
      labels:
        app: cart2
    spec:
      containers:
      - name: cart2
        image: lidiyaj/cartapi:2.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "31672"
---
apiVersion: v1
kind: Service
metadata:
  name: cart2
spec:
  type: NodePort
  selector:
    app: cart2
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32057