apiVersion: apps/v1
kind: Deployment
metadata:
  name: order2
spec:
  selector:
    matchLabels:
      app: order2
  template:
    metadata:
      labels:
        app: order2
    spec:
      containers:
      - name: order2
        image: lidiyaj/cartorderapi:2.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "31672"
---
apiVersion: v1
kind: Service
metadata:
  name: order2
spec:
  type: NodePort
  selector:
    app: order2
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32058